apiVersion: apps/v1
kind: Deployment
metadata:
  name: exchange-api
  labels:
    app: api-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-app
  template:
    metadata:
      labels:
        app: api-app
    spec:
      containers:
      - name: exchange-api
        image: ACCOUNT.dkr.ecr.REGION.amazonaws.com/REPO:IMAGEVERSION
        resources: 
          requests:
            memory: "64Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
        env:
          - name: PORT
            value: "5432"
          - name: DB
            valueFrom:
              secretKeyRef:
                name: postgresql-url-new
                key: url   #this is k8s secret


---
apiVersion: v1
kind: Service
metadata:
  name: exchange-api-svc
spec:
  selector:
    app: api-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
