apiVersion: apps/v1
kind: StatefulSet
metadata:
   name: jenkins-master
   namespace: jenkins-master
   labels:
     app: jenkins-master
spec:
  serviceName: "jenkins-svc"
  replicas: 1    
  selector:
    matchLabels:
      app: jenkins-master
  template:
    metadata:
      labels:
        app: jenkins-master
    spec:
      containers:
        - name: jenkins-master
          image: ACCOUNT.dkr.ecr.REGION.amazonaws.com/NAME:VERSION
          envFrom:
          - secretRef:
              name: jenkins-master-secret 
          env:
             - name: JAVA_OPTS
               value: -Djenkins.install.runSetupWizard=false
          ports:
             - name: http-port
               containerPort: 8080
             - name: jnlp-port
               containerPort: 50000
          volumeMounts:
             - name: jenkins-home
               mountPath: /var/jenkins_home
  volumeClaimTemplates:
  - metadata:
      name: jenkins-home
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 4Gi
