apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: jenkins-master
  name: jenkins-master-ingress
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: "jenkins-master.exchangeweb.net"
    http:
      paths:
      - path: /
        backend:
          serviceName: jenkins-master-svc
          servicePort: 8080


---
apiVersion: v1
kind: Service
metadata:
  namespace: jenkins-master
  name: jenkins-master-svc
  labels:
    app: jenkins-master
spec:
  selector:
    app: jenkins-master
  ports:
    - port: 8080
      targetPort: 8080
      name: http-port 
    - port: 50000
      targetPort: 50000   
      name: jnlp-port


---


apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: Immediate
